app:
  db:
    host: 127.0.0.1
    port: 3306
    dbname: fbpm1.0
    username: root
    password: root

spring:
  application:
    name: workflow
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${app.db.host}:${app.db.port}/${app.db.dbname}?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: ${app.db.username}
    password: ${app.db.password}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  redis:
    host: 10.10.65.43
  thymeleaf:
   encoding: UTF-8
   cache: false
   mode: LEGACYHTML5
   servlet:
     content-type: text/html
  profiles:
    active: test
eureka:
  client:
    enabled: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://10.10.65.43:8761/eureka/
server:
  port: 9000
  servlet:
    context-path: /${spring.application.name}

logging:
  level:
    com:
      crux: debug

flowable:
  checkProcessDefinitions: false
  synchronize: true
  common.app.idm-url: a
  database-schema-update: true
  async-executor-activate: true
  history-level: full